version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend